### PR TITLE
Fix missing buttons

### PR DESCRIPTION
**Pull request by eugenekotovhalliburton**
We need to remove unnecessary scaling

### CODE REVIEW

**Review by mastanarao — APPROVED** [review]
Tested changes works well

**Comment by sDavydiuk** [comment]
@eugenekotovhalliburton Please fix conflicts

**Comment by eugenekotovhalliburton** [comment]
> @eugenekotovhalliburton Please fix conflicts

Done

**Comment by ybova** [comment]
Should DPIUtil.autoScaleDown() call be removed as well at SWT_AWT:305 ?
Should such DPIUtil calls be removed in GTK version as well?

**Comment by eugenekotovhalliburton** [comment]
> Should DPIUtil.autoScaleDown() call be removed as well at SWT_AWT:305 ?
> Should such DPIUtil calls be removed in GTK version as well?

Done

**Pull request merged**
